version: v2
node_embed_size: 768
edge_embed_size: 384
symmetric: False
strict_time_conditioning: False
cond_vel_parameterization: True
node_features:
  c_s: ${model.node_embed_size}
  c_pos_emb: 128
  c_timestep_emb: 128
  max_num_res: 2000
  timestep_int: 1000
  embed_chain: False
  time_embedding_type: positional
  version: v2
edge_features:
  single_bias_transition_n: 2
  c_s: ${model.node_embed_size}
  c_p: ${model.edge_embed_size}
  relpos_k: 64
  feat_dim: 64
  num_bins: 22
  self_condition: True
  embed_chain: False
  embed_diffuse_mask: True
ipa:
  c_s: ${model.node_embed_size}
  c_z: ${model.edge_embed_size}
  c_hidden: 48
  no_heads: 16
  no_qk_points: 8
  no_v_points: 16
  seq_tfmr_num_heads: 12
  seq_tfmr_num_layers: 3
  num_blocks: 16

# ~437M params (large RMF)

